# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.Keywords'),
        ),
    ]
