# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
        migrations.AddField(
            model_name='focus',
            name='links',
            field=models.ManyToManyField(to='streamer.Links'),
        ),
    ]
