# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0003_auto_20160501_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='tweets',
            field=models.ManyToManyField(to='streamer.Tweets'),
        ),
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
    ]
