# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0004_auto_20160501_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focus',
            name='tweets',
        ),
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
