# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0008_auto_20160511_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
    ]
