# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0009_auto_20160525_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='/files')),
            ],
        ),
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
    ]
