# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0010_auto_20160719_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='files',
            field=models.ManyToManyField(to='streamer.FileModel'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_field',
            field=models.FileField(upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
    ]
