# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0012_auto_20160813_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
    ]
