# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0016_auto_20160822_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='file_field',
            new_name='file_ob',
        ),
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
    ]
