# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0017_auto_20160822_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='file_ob',
            new_name='file_field',
        ),
        migrations.AlterField(
            model_name='focus',
            name='keywords',
            field=models.ManyToManyField(to='streamer.KeyWords'),
        ),
    ]
